### ISSUE TITLE
Example without pre-generated C# sample? I.e Manual C# example with a few simple container/component boxes

### ISSUE THREAD

**Issue by pjmagee** [SlavaVedernikov/C4InterFlow#108]
I'm finding it hard to generate diagrams trying to manually do it. A manual example i.e Context/Container/Component not depending on eShop would be useful.

I was trying to dig into how it is trying to resolve or recognise, but im finding it hard, and then I am finding some things which didnt make sense to me such as 

`ALIAS` being part of the roslyn analyzer code but is not part of the Interfaces, so it's not apparant they are even required.

**Comment by SlavaVedernikov** [comment]
Could you please explain what exactly you are trying to achieve. e.g.

1. Generate AaC in C# or YAML from C# codebase and then generate diagrams from AaC
2. Write AaC manually in C#, YAML or JSON and then generate diagrams from AaC
3. Something else..?

If you are writing AaC manually, the easiest approach would be to use YAML.

**Comment by SlavaVedernikov** [comment]
Using ALIAS is just the implementation details, that's why it is not part of Interface definitions for structures.
Note that it is `private` e.g. 
```CSharp
private static readonly string ALIAS
```
It is used as a path to a type of a structure. I think it could have been done differently (e.g. using Type instances), but I think it may cause some compilation issues as some types may not exists when they are referenced in code in the middle of AaC generation (even though all types will probably exist by the end of AaC generation). Anyway this is something we can explore.

```CSharp
// <auto-generated/>
using C4InterFlow.Structures;
using C4InterFlow.Structures.Interfaces;

namespace DotNetEShop.SoftwareSystems
{
    public partial class BasketApi
    {
        public partial class Containers
        {
            public partial class Data
            {
                public partial class Components
                {
                    public partial class RedisBasketRepository : IComponentInstance
                    {
                        private static readonly string ALIAS = "DotNetEShop.SoftwareSystems.BasketApi.Containers.Data.Components.RedisBasketRepository";
                        public static Component Instance => new Component(DotNetEShop.SoftwareSystems.BasketApi.Containers.Data.ALIAS, ALIAS, "Redis Basket Repository")
                        {
                            ComponentType = ComponentType.None,
                            Description = "",
                            Technology = ""
                        };
                    }
                }
            }
        }
    }
}
```

**Comment by pjmagee** [comment]
> Could you please explain what exactly you are trying to achieve. e.g.
> 
> 1. Generate AaC in C# or YAML from C# codebase and then generate diagrams from AaC
> 2. Write AaC manually in C#, YAML or JSON and then generate diagrams from AaC
> 3. Something else..?
> 
> If you are writing AaC manually, the easiest (and **recommended**) approach would be to use **YAML**. YAML AaC will also have better support for new features in the future.

Yes number 2, I really think number one is interesting as well but I deal with a lot of multi technologies and platforms and manual is most interesting for me because i am very comfortable using C#. I was coming here after looking into c4 model CSharp project which I think you had some inspiration from there.

**Comment by SlavaVedernikov** [comment]
I would strongly suggest for you to try **YAML** Architecture as Code.  

As I said earlier, it is easier and it will get more attention in the future as it seems to be the most popular approach and we don't have many contributors yet to keep other approaches constantly up to date.

If you still prefer using **C#** AaC, then writing it should be pretty much what you see being generated in [DotNetEshop sample](https://github.com/SlavaVedernikov/C4InterFlow/tree/master/Samples/dotnet.eShop/DotNetEShop/SoftwareSystems)
If you have issues with it, please post example C# AaC and I'll look into it.

**Comment by SlavaVedernikov** [comment]
@pjmagee just wanted to let you know that I've reviewed and simplified the C# AaC.
Now there is no need for ALIAS fields and it is strongly-types i.e. no string structure aliases used anymore.

I've also added [C# AaC code to ToDo App sample](https://github.com/SlavaVedernikov/C4InterFlow/tree/master/Samples/ToDoApp/CSharp/ToDoAppExample/SoftwareSystems), please check.

Let me know how you get on if you choose to stick with C# AaC.

**Comment by SlavaVedernikov** [comment]
@pjmagee FYI, I've improved it further by eliminating the need to repeat type names in C# AaC definitions e.g.

Before
```CSharp
public partial class Interfaces
{
	public partial class ViewTasks : IInterfaceInstance
	{
		public static Interface Instance => new Interface(typeof(ViewTasks))
		{
			Flow = new Flow(Interface.GetAlias<ViewTasks>())
				.Use<WebApi.Interfaces.GetTasks>(),
		};
	}
}
```
After
```CSharp
public partial class Interfaces
{
	public partial class ViewTasks : IInterfaceInstance
	{
		public Interface Instance => new Interface(GetType())
		{
			Flow = new Flow(Interface.GetAlias(GetType()))
				.Use<WebApi.Interfaces.GetTasks>(),
		};
	}
}
```
