### ISSUE TITLE
Cli Starter code is outdated?

### ISSUE THREAD

**Issue by pjmagee** [SlavaVedernikov/C4InterFlow#109]
Copying the documentation approach regarding creating a new `cli` project and using the sample code in the docs gives compiler errors, some of the code doesnt seem to be compilable anymore. I managed to get it working by removing `Build()`/`Logging()` and using `Run()`

**Comment by SlavaVedernikov** [comment]
I've tested it and it works for me assuming you are referring to the following code snippet on [Command-Line-Interface-(CLI)](https://github.com/SlavaVedernikov/C4InterFlow/wiki/Command-Line-Interface-(CLI)) wiki page.
```CSharp
using System.CommandLine.Builder;
using System.CommandLine.Parsing;
using C4InterFlow.Cli.Root;
using C4InterFlow.Cli.Commands;
using C4InterFlow.Cli.Extensions;

var rootCommandBuilder = RootCommandBuilder
    .CreateDefaultBuilder(args)
    .Configure(context =>
    {
        context.Add<DrawDiagramsCommand>();
        context.Add<QueryUseFlowsCommand>();
        context.Add<QueryByInputCommand>();
        context.Add<ExecuteAaCStrategyCommand>();
    });

await new CommandLineBuilder(rootCommandBuilder.Build())
    .UseDefaults().UseLogging().Build().InvokeAsync(args);
```

Could you please provide more details e.g. your environment set-up, error(s) etc.?

**Comment by SlavaVedernikov** [comment]
Yes, NuGet package is behind. Is this how you found C4InterFlow..?
I'll try to update the NuGet package in the near future.

**Comment by pjmagee** [comment]
> Yes, NuGet package is behind. Is this how you found C4InterFlow..? I'll try to update the NuGet package in the near future.

I found it from c4model.com if my memory is right, I was checking a few different C# solutions and this project seems very interesting, it has a strong vision compared to some alternatives and is C# based which is my strength

**Comment by SlavaVedernikov** [comment]
FYI, I've just released [C4InterFlow.Automation - v1.7.0](https://www.nuget.org/packages/C4InterFlow.Automation) NuGet package

**Comment by pjmagee** [comment]
> FYI, I've just released [C4InterFlow.Automation - v1.7.0](https://www.nuget.org/packages/C4InterFlow.Automation) NuGet package

I have a feeling there is an issue with the NuGet but not when you are referencing the code within the project. I will try and import the source of the project and see if the behaviour changes.

with the nuget it doesnt seem to pick up the interfaces, despite the only difference from the sample and my version is i am using the nuget, and you are referencing the code directly.

**Comment by SlavaVedernikov** [comment]
@pjmagee try [C4InterFlow.Automation - v1.8.0](https://www.nuget.org/packages/C4InterFlow.Automation)  

It has all the latest changes.
