### ISSUE TITLE
I cannot get the sample app working still

### ISSUE THREAD

**Issue by pjmagee** [SlavaVedernikov/C4InterFlow#125]
I even spent time debugging the app, and i am going a bit crazy...

I don't think i understand the pattern/wildcard logic that is required to pass in for `--interfaces`. As I was debugging, I was having this function `private bool NamespaceMatchesPattern(string? namespaceName, string pattern)` return false 

for my libraries namespaces/types: 

e.g:

`AaC.SoftwareSystems.ApigeeEdge` was never returned with pattern `-i AaC.SoftwareSystems.*.Containers.*.Interfaces.*`

Is there a simpler configuration? Find all types where they inherit the library interfaces, and include them? 

![image](https://github.com/user-attachments/assets/1da1a1bb-8112-4eb3-9289-5ed9a8eab6c5)

![image](https://github.com/user-attachments/assets/05ced3a9-19f3-46c6-9625-99cebda20f52)

The dll is correctly loaded, I was stepping through each line of the library code, as I was struggling to understand why this is not working, but this function in particular seems to return false which I would not expect: `NamespaceMatchesPattern` so I am thinking something is wrong either with my simple code or am not understanding the required `-i` argument for `draw-diagrams`.

![image](https://github.com/user-attachments/assets/e881a396-b0e5-4ad6-90cf-aa0c0bab3fd0)
![image](https://github.com/user-attachments/assets/4f7da78e-fa59-4e72-b424-41ce31776eaf)

I was expecting the System and basic container to be somehow detected

**Comment by SlavaVedernikov** [comment]
@pjmagee I noticed that you are defining your `ApigeeEdge` Software system as follows

```CSharp
namespace AaC.SoftwareSystems;

public partial class ApigeeEdge: ISoftwareSystemInstance
{
    public SoftwareSystem Instance => new (nameof(ApigeeEdge), "APIGEE Edge", "APIGEE Edge is a platform for developing an managing APIs.");
}
```

This would not work as the `SoftwareSystem` constructor you are using requires the full alias (i.e. namespace + class hierarchy "." delimited) and you are using `nameof(ApigeeEdge)`, which would return only `"ApigeeEdge"`

I suggest you use a different `SoftwareSystem` constructor i.e. `public SoftwareSystem(Type type)` as follows

```CSharp
namespace AaC.SoftwareSystems;

public partial class ApigeeEdge: ISoftwareSystemInstance
{
    public SoftwareSystem Instance => new (GetType()) {
        Label = "APIGEE Edge",
        Description = "APIGEE Edge is a platform for developing an managing APIs."
    };
}
```

**Comment by SlavaVedernikov** [comment]
BTW, I provide [Architecture as Code Implementation services](https://www.c4interflow.com/services). All I need from you are **existing diagrams** in any format and some of your team's time for **Q&A** and **Review** workshops.

Submit your request [here](https://www.c4interflow.com/services) if you're interested.

**Comment by pjmagee** [comment]
Thanks, I will have another go at this today! Right now, i am hoping to add an agenda item internally to share across all of the company on AaC in general, and its more about educating and showing some options, one of those I will hopefully use your project to demonstrate the concepts!!
